// -------------------------------------------------------------
// 
// File Name: D:\buck_conv\ip_pwm\hdlsrc\untitled\pwm_ip_src_pwm.v
// Created: 2026-02-18 15:31:14
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 1e-06
// Target subsystem base rate: 1e-06
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        1e-06
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// pwm_out                       ce_out        1e-06
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pwm_ip_src_pwm
// Source Path: untitled/pwm
// Hierarchy Level: 0
// Model version: 1.0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pwm_ip_src_pwm
          (clk,
           reset,
           clk_enable,
           duty,
           ce_out,
           pwm_out);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] duty;  // int16
  output  ce_out;
  output  pwm_out;


  wire enb;
  wire [15:0] count_step;  // uint16
  wire [15:0] count_from_1;  // uint16
  reg [15:0] Counter_Limited_out1;  // uint16
  wire [15:0] count;  // uint16
  wire needToWrap;
  wire [15:0] count_value;  // uint16
  wire signed [31:0] Gain_mul_temp;  // sfix32_En5
  wire signed [15:0] Gain_out1;  // int16
  wire signed [16:0] Relational_Operator_1;  // sfix17
  wire signed [16:0] Relational_Operator_2;  // sfix17
  wire Relational_Operator_out1;


  assign count_step = 16'b0000000000000001;

  assign count_from_1 = 16'b0000000000000000;

  assign enb = clk_enable;

  assign count = Counter_Limited_out1 + count_step;

  assign needToWrap = Counter_Limited_out1 >= 16'b0000001111100111;

  assign count_value = (needToWrap == 1'b0 ? count :
              count_from_1);

  // Count limited, Unsigned Counter
  //  initial value   = 0
  //  step value      = 1
  //  count to value  = 999
  always @(posedge clk or posedge reset)
    begin : Counter_Limited_process
      if (reset == 1'b1) begin
        Counter_Limited_out1 <= 16'b0000000000000000;
      end
      else begin
        if (enb) begin
          Counter_Limited_out1 <= count_value;
        end
      end
    end

  assign Gain_mul_temp = 16'sb0111110011100000 * duty;
  assign Gain_out1 = Gain_mul_temp[20:5];

  assign Relational_Operator_1 = {1'b0, Counter_Limited_out1};
  assign Relational_Operator_2 = {Gain_out1[15], Gain_out1};
  assign Relational_Operator_out1 = Relational_Operator_1 < Relational_Operator_2;

  assign pwm_out = Relational_Operator_out1;

  assign ce_out = clk_enable;

endmodule  // pwm_ip_src_pwm

