// -------------------------------------------------------------
// 
// File Name: D:\buck_conv\ip_controller\hdlsrc\controller_only\controller_ip_reset_sync.v
// Created: 2026-02-18 15:33:50
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: controller_ip_reset_sync
// Source Path: controller_ip/controller_ip_reset_sync
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module controller_ip_reset_sync
          (clk,
           reset_in,
           reset_out);


  input   clk;
  input   reset_in;  // ufix1
  output  reset_out;  // ufix1


  wire enb;
  wire const_0;  // ufix1
  wire const_1;  // ufix1
  reg  reset_pipe;  // ufix1
  reg  reset_out_1;  // ufix1


  assign const_0 = 1'b0;

  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge clk or posedge reset_in)
    begin : reg_reset_pipe_process
      if (reset_in == 1'b1) begin
        reset_pipe <= 1'b1;
      end
      else begin
        if (enb) begin
          reset_pipe <= const_0;
        end
      end
    end

  always @(posedge clk or posedge reset_in)
    begin : reg_reset_delay_process
      if (reset_in == 1'b1) begin
        reset_out_1 <= 1'b1;
      end
      else begin
        if (enb) begin
          reset_out_1 <= reset_pipe;
        end
      end
    end

  assign reset_out = reset_out_1;

endmodule  // controller_ip_reset_sync

