// -------------------------------------------------------------
// 
// File Name: D:\buck_conv\ip_pwm\hdlsrc\untitled\pwm_ip.v
// Created: 2026-02-18 15:31:20
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: -1
// Target subsystem base rate: -1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pwm_ip
// Source Path: pwm_ip
// Hierarchy Level: 0
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pwm_ip
          (IPCORE_CLK,
           IPCORE_RESETN,
           AXI4_Lite_ACLK,
           AXI4_Lite_ARESETN,
           AXI4_Lite_AWADDR,
           AXI4_Lite_AWVALID,
           AXI4_Lite_WDATA,
           AXI4_Lite_WSTRB,
           AXI4_Lite_WVALID,
           AXI4_Lite_BREADY,
           AXI4_Lite_ARADDR,
           AXI4_Lite_ARVALID,
           AXI4_Lite_RREADY,
           pwm_out,
           AXI4_Lite_AWREADY,
           AXI4_Lite_WREADY,
           AXI4_Lite_BRESP,
           AXI4_Lite_BVALID,
           AXI4_Lite_ARREADY,
           AXI4_Lite_RDATA,
           AXI4_Lite_RRESP,
           AXI4_Lite_RVALID);


  input   IPCORE_CLK;  // ufix1
  input   IPCORE_RESETN;  // ufix1
  input   AXI4_Lite_ACLK;  // ufix1
  input   AXI4_Lite_ARESETN;  // ufix1
  input   [15:0] AXI4_Lite_AWADDR;  // ufix16
  input   AXI4_Lite_AWVALID;  // ufix1
  input   [31:0] AXI4_Lite_WDATA;  // ufix32
  input   [3:0] AXI4_Lite_WSTRB;  // ufix4
  input   AXI4_Lite_WVALID;  // ufix1
  input   AXI4_Lite_BREADY;  // ufix1
  input   [15:0] AXI4_Lite_ARADDR;  // ufix16
  input   AXI4_Lite_ARVALID;  // ufix1
  input   AXI4_Lite_RREADY;  // ufix1
  output  pwm_out;  // ufix1
  output  AXI4_Lite_AWREADY;  // ufix1
  output  AXI4_Lite_WREADY;  // ufix1
  output  [1:0] AXI4_Lite_BRESP;  // ufix2
  output  AXI4_Lite_BVALID;  // ufix1
  output  AXI4_Lite_ARREADY;  // ufix1
  output  [31:0] AXI4_Lite_RDATA;  // ufix32
  output  [1:0] AXI4_Lite_RRESP;  // ufix2
  output  AXI4_Lite_RVALID;  // ufix1


  wire reset;
  wire [31:0] ip_timestamp;  // ufix32
  wire reset_cm;  // ufix1
  wire reset_internal;  // ufix1
  wire reset_before_sync;  // ufix1
  wire write_axi_enable;  // ufix1
  wire signed [15:0] write_duty;  // sfix16
  wire ce_out_sig;  // ufix1
  wire pwm_out_sig;  // ufix1


  assign ip_timestamp = 32'b10011011000110100010001110011011;

  assign reset_cm =  ~ IPCORE_RESETN;

  assign reset_before_sync = reset_cm | reset_internal;

  pwm_ip_reset_sync u_pwm_ip_reset_sync_inst (.clk(IPCORE_CLK),  // ufix1
                                              .reset_in(reset_before_sync),  // ufix1
                                              .reset_out(reset)
                                              );

  pwm_ip_axi_lite u_pwm_ip_axi_lite_inst (.reset(reset),
                                          .AXI4_Lite_ACLK(AXI4_Lite_ACLK),  // ufix1
                                          .AXI4_Lite_ARESETN(AXI4_Lite_ARESETN),  // ufix1
                                          .AXI4_Lite_AWADDR(AXI4_Lite_AWADDR),  // ufix16
                                          .AXI4_Lite_AWVALID(AXI4_Lite_AWVALID),  // ufix1
                                          .AXI4_Lite_WDATA(AXI4_Lite_WDATA),  // ufix32
                                          .AXI4_Lite_WSTRB(AXI4_Lite_WSTRB),  // ufix4
                                          .AXI4_Lite_WVALID(AXI4_Lite_WVALID),  // ufix1
                                          .AXI4_Lite_BREADY(AXI4_Lite_BREADY),  // ufix1
                                          .AXI4_Lite_ARADDR(AXI4_Lite_ARADDR),  // ufix16
                                          .AXI4_Lite_ARVALID(AXI4_Lite_ARVALID),  // ufix1
                                          .AXI4_Lite_RREADY(AXI4_Lite_RREADY),  // ufix1
                                          .read_ip_timestamp(ip_timestamp),  // ufix32
                                          .AXI4_Lite_AWREADY(AXI4_Lite_AWREADY),  // ufix1
                                          .AXI4_Lite_WREADY(AXI4_Lite_WREADY),  // ufix1
                                          .AXI4_Lite_BRESP(AXI4_Lite_BRESP),  // ufix2
                                          .AXI4_Lite_BVALID(AXI4_Lite_BVALID),  // ufix1
                                          .AXI4_Lite_ARREADY(AXI4_Lite_ARREADY),  // ufix1
                                          .AXI4_Lite_RDATA(AXI4_Lite_RDATA),  // ufix32
                                          .AXI4_Lite_RRESP(AXI4_Lite_RRESP),  // ufix2
                                          .AXI4_Lite_RVALID(AXI4_Lite_RVALID),  // ufix1
                                          .write_axi_enable(write_axi_enable),  // ufix1
                                          .write_duty(write_duty),  // sfix16
                                          .reset_internal(reset_internal)  // ufix1
                                          );

  pwm_ip_dut u_pwm_ip_dut_inst (.clk(IPCORE_CLK),  // ufix1
                                .reset(reset),
                                .dut_enable(write_axi_enable),  // ufix1
                                .duty(write_duty),  // sfix16
                                .ce_out(ce_out_sig),  // ufix1
                                .pwm_out(pwm_out_sig)  // ufix1
                                );

  assign pwm_out = pwm_out_sig;

endmodule  // pwm_ip

