// -------------------------------------------------------------
// 
// File Name: D:\buck_conv\ip_pwm\hdlsrc\untitled\pwm_ip_dut.v
// Created: 2026-02-18 15:31:20
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pwm_ip_dut
// Source Path: pwm_ip/pwm_ip_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pwm_ip_dut
          (clk,
           reset,
           dut_enable,
           duty,
           ce_out,
           pwm_out);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   signed [15:0] duty;  // sfix16
  output  ce_out;  // ufix1
  output  pwm_out;  // ufix1


  wire enb;
  wire ce_out_sig;  // ufix1
  wire pwm_out_sig;  // ufix1


  assign enb = dut_enable;

  pwm_ip_src_pwm u_pwm_ip_src_pwm (.clk(clk),
                                   .clk_enable(enb),
                                   .reset(reset),
                                   .duty(duty),  // sfix16
                                   .ce_out(ce_out_sig),  // ufix1
                                   .pwm_out(pwm_out_sig)  // ufix1
                                   );

  assign ce_out = ce_out_sig;

  assign pwm_out = pwm_out_sig;

endmodule  // pwm_ip_dut

