// -------------------------------------------------------------
// 
// File Name: D:\buck_conv\ip_controller\hdlsrc\controller_only\controller_ip_src_controller.v
// Created: 2026-02-18 15:33:47
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// 
// -- -------------------------------------------------------------
// -- Rate and Clocking Details
// -- -------------------------------------------------------------
// Model base rate: 5e-05
// Target subsystem base rate: 5e-05
// 
// 
// Clock Enable  Sample Time
// -- -------------------------------------------------------------
// ce_out        5e-05
// -- -------------------------------------------------------------
// 
// 
// Output Signal                 Clock Enable  Sample Time
// -- -------------------------------------------------------------
// duty                          ce_out        5e-05
// -- -------------------------------------------------------------
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: controller_ip_src_controller
// Source Path: controller_only/controller
// Hierarchy Level: 0
// Model version: 1.14
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module controller_ip_src_controller
          (clk,
           reset,
           clk_enable,
           vmeans,
           vref,
           ce_out,
           duty);


  input   clk;
  input   reset;
  input   clk_enable;
  input   signed [15:0] vmeans;  // int16
  input   signed [15:0] vref;  // int16
  output  ce_out;
  output  signed [15:0] duty;  // int16


  wire enb;
  wire signed [15:0] Error_Calc;  // int16
  wire signed [31:0] Kp_Gain_mul_temp;  // sfix32_En19
  wire signed [15:0] Kp_Gain_out1;  // int16
  wire signed [31:0] Ki_Gain_mul_temp;  // sfix32_En6
  wire signed [15:0] Ki_Gain_out1;  // int16
  wire signed [31:0] Ki_mult_mul_temp;  // sfix32
  wire signed [15:0] Ki_mult_out1;  // int16
  wire signed [15:0] Constant_out1;  // int16
  wire signed [15:0] Constant1_out1;  // int16
  wire signed [15:0] I_sum_out1;  // int16
  reg signed [15:0] Unit_Delay_out1;  // int16
  wire signed [15:0] PI_sum_out1;  // int16
  wire Relational_Operator1_out1;
  wire Relational_Operator_out1;
  wire Saturated_out1;
  wire Not_Sat_out1;
  wire signed [15:0] Data_Type_Conversion_out1;  // int16
  reg signed [15:0] Unit_Delay1_out1;  // int16
  wire signed [31:0] Product_mul_temp;  // sfix32
  wire signed [15:0] Product_out1;  // int16
  wire signed [15:0] Duty_Limit_out1;  // int16
  wire signed [31:0] Duty_Scale_cast;  // sfix32_E2
  wire signed [15:0] Duty_Scale_out1;  // int16
  reg signed [15:0] Unit_Delay2_out1;  // int16


  assign Error_Calc = vref + vmeans;

  assign Kp_Gain_mul_temp = 16'sb0110011001100110 * Error_Calc;
  assign Kp_Gain_out1 = {{3{Kp_Gain_mul_temp[31]}}, Kp_Gain_mul_temp[31:19]};

  assign Ki_Gain_mul_temp = 16'sb0111110100000000 * vref;
  assign Ki_Gain_out1 = Ki_Gain_mul_temp[21:6];

  assign Ki_mult_mul_temp = Error_Calc * Ki_Gain_out1;
  assign Ki_mult_out1 = Ki_mult_mul_temp[15:0];

  assign Constant_out1 = 16'sb0000000000000001;

  assign Constant1_out1 = 16'sb0000000000000000;

  assign enb = clk_enable;

  always @(posedge clk or posedge reset)
    begin : Unit_Delay_process
      if (reset == 1'b1) begin
        Unit_Delay_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay_out1 <= I_sum_out1;
        end
      end
    end

  assign Relational_Operator1_out1 = PI_sum_out1 < Constant1_out1;

  assign Relational_Operator_out1 = PI_sum_out1 > Constant_out1;

  assign Saturated_out1 = Relational_Operator_out1 | Relational_Operator1_out1;

  assign Not_Sat_out1 =  ~ Saturated_out1;

  assign Data_Type_Conversion_out1 = {15'b0, Not_Sat_out1};

  always @(posedge clk or posedge reset)
    begin : Unit_Delay1_process
      if (reset == 1'b1) begin
        Unit_Delay1_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay1_out1 <= Data_Type_Conversion_out1;
        end
      end
    end

  assign Product_mul_temp = Ki_mult_out1 * Unit_Delay1_out1;
  assign Product_out1 = Product_mul_temp[15:0];

  assign I_sum_out1 = Product_out1 + Unit_Delay_out1;

  assign PI_sum_out1 = Kp_Gain_out1 + I_sum_out1;

  assign Duty_Limit_out1 = (PI_sum_out1 > 16'sb0000000000000001 ? 16'sb0000000000000001 :
              (PI_sum_out1 < 16'sb0000000000000000 ? 16'sb0000000000000000 :
              PI_sum_out1));

  assign Duty_Scale_cast = {{2{Duty_Limit_out1[15]}}, {Duty_Limit_out1, 14'b00000000000000}};
  assign Duty_Scale_out1 = {Duty_Scale_cast[13:0], 2'b00};

  always @(posedge clk or posedge reset)
    begin : Unit_Delay2_process
      if (reset == 1'b1) begin
        Unit_Delay2_out1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          Unit_Delay2_out1 <= Duty_Scale_out1;
        end
      end
    end

  assign duty = Unit_Delay2_out1;

  assign ce_out = clk_enable;

endmodule  // controller_ip_src_controller

