// -------------------------------------------------------------
// 
// File Name: D:\buck_conv\ip_controller\hdlsrc\controller_only\controller_ip_addr_decoder.v
// Created: 2026-02-18 15:33:50
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: controller_ip_addr_decoder
// Source Path: controller_ip/controller_ip_axi_lite/controller_ip_addr_decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module controller_ip_addr_decoder
          (clk,
           reset,
           data_write,
           addr_write,
           wr_enb,
           addr_read,
           rd_enb,
           read_ip_timestamp,
           read_duty,
           data_read,
           write_axi_enable,
           write_vmeans,
           write_vref);


  input   clk;
  input   reset;
  input   [31:0] data_write;  // ufix32
  input   [13:0] addr_write;  // ufix14
  input   wr_enb;  // ufix1
  input   [13:0] addr_read;  // ufix14
  input   rd_enb;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  input   signed [15:0] read_duty;  // sfix16
  output  [31:0] data_read;  // ufix32
  output  write_axi_enable;  // ufix1
  output  signed [15:0] write_vmeans;  // sfix16
  output  signed [15:0] write_vref;  // sfix16


  wire enb;
  wire [6:0] address_select_level1;  // ufix7
  wire const_1;  // ufix1
  reg [31:0] read_reg_ip_timestamp;  // ufix32
  reg signed [15:0] read_reg_duty;  // sfix16
  wire [31:0] data_slice_duty_1;  // ufix32
  wire [31:0] const_0;  // ufix32
  reg [31:0] mux_out0_level1;  // ufix32
  wire decode_sel_axi_enable_1_1;  // ufix1
  wire reg_enb_axi_enable_1_1;  // ufix1
  wire data_in_axi_enable;  // ufix1
  reg  data_reg_axi_enable_1_1;  // ufix1
  wire decode_sel_vmeans_1_1;  // ufix1
  wire reg_enb_vmeans_1_1;  // ufix1
  wire signed [15:0] data_in_vmeans;  // sfix16
  reg signed [15:0] data_reg_vmeans_1_1;  // sfix16
  wire decode_sel_vref_1_1;  // ufix1
  wire reg_enb_vref_1_1;  // ufix1
  wire signed [15:0] data_in_vref;  // sfix16
  reg signed [15:0] data_reg_vref_1_1;  // sfix16


  assign address_select_level1 = addr_read[6:0];

  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge clk or posedge reset)
    begin : reg_ip_timestamp_process
      if (reset == 1'b1) begin
        read_reg_ip_timestamp <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_ip_timestamp <= read_ip_timestamp;
        end
      end
    end

  always @(posedge clk or posedge reset)
    begin : reg_duty_process
      if (reset == 1'b1) begin
        read_reg_duty <= 16'sb0000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_duty <= read_duty;
        end
      end
    end

  assign data_slice_duty_1 = {{16{read_reg_duty[15]}}, read_reg_duty};

  assign const_0 = 32'b00000000000000000000000000000000;

  always @(address_select_level1, const_0, data_slice_duty_1, read_reg_ip_timestamp) begin
    case ( address_select_level1)
      7'b0000010 :
        begin
          mux_out0_level1 = read_reg_ip_timestamp;
        end
      7'b1000010 :
        begin
          mux_out0_level1 = data_slice_duty_1;
        end
      default :
        begin
          mux_out0_level1 = const_0;
        end
    endcase
  end

  assign data_read = mux_out0_level1;

  assign decode_sel_axi_enable_1_1 = addr_write == 14'b00000000000001;

  assign reg_enb_axi_enable_1_1 = decode_sel_axi_enable_1_1 & wr_enb;

  assign data_in_axi_enable = data_write[0];

  always @(posedge clk or posedge reset)
    begin : reg_axi_enable_1_1_process
      if (reset == 1'b1) begin
        data_reg_axi_enable_1_1 <= 1'b1;
      end
      else begin
        if (enb && reg_enb_axi_enable_1_1) begin
          data_reg_axi_enable_1_1 <= data_in_axi_enable;
        end
      end
    end

  assign write_axi_enable = data_reg_axi_enable_1_1;

  assign decode_sel_vmeans_1_1 = addr_write == 14'b00000001000000;

  assign reg_enb_vmeans_1_1 = decode_sel_vmeans_1_1 & wr_enb;

  assign data_in_vmeans = $signed(data_write[15:0]);

  always @(posedge clk or posedge reset)
    begin : reg_vmeans_1_1_process
      if (reset == 1'b1) begin
        data_reg_vmeans_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_vmeans_1_1) begin
          data_reg_vmeans_1_1 <= data_in_vmeans;
        end
      end
    end

  assign write_vmeans = data_reg_vmeans_1_1;

  assign decode_sel_vref_1_1 = addr_write == 14'b00000001000001;

  assign reg_enb_vref_1_1 = decode_sel_vref_1_1 & wr_enb;

  assign data_in_vref = $signed(data_write[15:0]);

  always @(posedge clk or posedge reset)
    begin : reg_vref_1_1_process
      if (reset == 1'b1) begin
        data_reg_vref_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_vref_1_1) begin
          data_reg_vref_1_1 <= data_in_vref;
        end
      end
    end

  assign write_vref = data_reg_vref_1_1;

endmodule  // controller_ip_addr_decoder

