// -------------------------------------------------------------
// 
// File Name: D:\buck_conv\ip_controller\hdlsrc\controller_only\controller_ip_dut.v
// Created: 2026-02-18 15:33:50
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: controller_ip_dut
// Source Path: controller_ip/controller_ip_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module controller_ip_dut
          (clk,
           reset,
           dut_enable,
           vmeans,
           vref,
           ce_out,
           duty);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   signed [15:0] vmeans;  // sfix16
  input   signed [15:0] vref;  // sfix16
  output  ce_out;  // ufix1
  output  signed [15:0] duty;  // sfix16


  wire enb;
  wire ce_out_sig;  // ufix1
  wire signed [15:0] duty_sig;  // sfix16


  assign enb = dut_enable;

  controller_ip_src_controller u_controller_ip_src_controller (.clk(clk),
                                                               .clk_enable(enb),
                                                               .reset(reset),
                                                               .vmeans(vmeans),  // sfix16
                                                               .vref(vref),  // sfix16
                                                               .ce_out(ce_out_sig),  // ufix1
                                                               .duty(duty_sig)  // sfix16
                                                               );

  assign ce_out = ce_out_sig;

  assign duty = duty_sig;

endmodule  // controller_ip_dut

