// -------------------------------------------------------------
// 
// File Name: D:\buck_conv\ip_pwm\hdlsrc\untitled\pwm_ip_addr_decoder.v
// Created: 2026-02-18 15:31:20
// 
// Generated by MATLAB 25.1, HDL Coder 25.1, and Simulink 25.1
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: pwm_ip_addr_decoder
// Source Path: pwm_ip/pwm_ip_axi_lite/pwm_ip_addr_decoder
// Hierarchy Level: 2
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module pwm_ip_addr_decoder
          (clk,
           reset,
           data_write,
           addr_write,
           wr_enb,
           addr_read,
           rd_enb,
           read_ip_timestamp,
           data_read,
           write_axi_enable,
           write_duty);


  input   clk;
  input   reset;
  input   [31:0] data_write;  // ufix32
  input   [13:0] addr_write;  // ufix14
  input   wr_enb;  // ufix1
  input   [13:0] addr_read;  // ufix14
  input   rd_enb;  // ufix1
  input   [31:0] read_ip_timestamp;  // ufix32
  output  [31:0] data_read;  // ufix32
  output  write_axi_enable;  // ufix1
  output  signed [15:0] write_duty;  // sfix16


  wire enb;
  wire [1:0] address_select_level1;  // ufix2
  wire const_1;  // ufix1
  reg [31:0] read_reg_ip_timestamp;  // ufix32
  wire [31:0] const_0;  // ufix32
  wire [31:0] mux_out0_level1;  // ufix32
  wire decode_sel_axi_enable_1_1;  // ufix1
  wire reg_enb_axi_enable_1_1;  // ufix1
  wire data_in_axi_enable;  // ufix1
  reg  data_reg_axi_enable_1_1;  // ufix1
  wire decode_sel_duty_1_1;  // ufix1
  wire reg_enb_duty_1_1;  // ufix1
  wire signed [15:0] data_in_duty;  // sfix16
  reg signed [15:0] data_reg_duty_1_1;  // sfix16


  assign address_select_level1 = addr_read[1:0];

  assign const_1 = 1'b1;

  assign enb = const_1;

  always @(posedge clk or posedge reset)
    begin : reg_ip_timestamp_process
      if (reset == 1'b1) begin
        read_reg_ip_timestamp <= 32'b00000000000000000000000000000000;
      end
      else begin
        if (enb) begin
          read_reg_ip_timestamp <= read_ip_timestamp;
        end
      end
    end

  assign const_0 = 32'b00000000000000000000000000000000;

  assign mux_out0_level1 = (address_select_level1 == 2'b10 ? read_reg_ip_timestamp :
              const_0);

  assign data_read = mux_out0_level1;

  assign decode_sel_axi_enable_1_1 = addr_write == 14'b00000000000001;

  assign reg_enb_axi_enable_1_1 = decode_sel_axi_enable_1_1 & wr_enb;

  assign data_in_axi_enable = data_write[0];

  always @(posedge clk or posedge reset)
    begin : reg_axi_enable_1_1_process
      if (reset == 1'b1) begin
        data_reg_axi_enable_1_1 <= 1'b1;
      end
      else begin
        if (enb && reg_enb_axi_enable_1_1) begin
          data_reg_axi_enable_1_1 <= data_in_axi_enable;
        end
      end
    end

  assign write_axi_enable = data_reg_axi_enable_1_1;

  assign decode_sel_duty_1_1 = addr_write == 14'b00000001000000;

  assign reg_enb_duty_1_1 = decode_sel_duty_1_1 & wr_enb;

  assign data_in_duty = $signed(data_write[15:0]);

  always @(posedge clk or posedge reset)
    begin : reg_duty_1_1_process
      if (reset == 1'b1) begin
        data_reg_duty_1_1 <= 16'sb0000000000000000;
      end
      else begin
        if (enb && reg_enb_duty_1_1) begin
          data_reg_duty_1_1 <= data_in_duty;
        end
      end
    end

  assign write_duty = data_reg_duty_1_1;

endmodule  // pwm_ip_addr_decoder

